### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by BitNetOps**
## Description

Add *.ubuntu.com to the filter. This allow the following 2 commands to work:

sudo apt-get udpate -y
sudo apt-get upgrade -y

_Describe the changes needed_

### CODE REVIEW

**Comment by BitNetOps** [comment]
trying again

**Review by BitEtherSecops — APPROVED** [review]
looked right

**Comment by BitEtherSecops** [comment]
reviewed

**Review by BitEtherSecops — APPROVED** [review]

**Review by BitEtherSecops — APPROVED** [review]

**Review by BitEtherSecops — APPROVED** [review]

**Review by BitEtherSecops — APPROVED** [review]

**Review by BitEtherSecops — APPROVED** [review]

**Review by BitEtherSecops — APPROVED** [review]
looked good

**Review by BitEtherSecops — APPROVED** [review]

**Review by BitEtherSecops — APPROVED** [review]

**Review by BitEtherSecops — APPROVED** [review]
completed

**Pull request closed without merging**
